### ISSUE TITLE
no images are displayed

### ISSUE THREAD

**Issue by uliw** [shg/org-inline-pdf.el#5]
```
[[./graphs/co2_vs_t.pdf]]
```
and ctrl-c ctrl-x ctrl-v result in no visible change. Neither are any svg files produced

**Comment by shg** [comment]
Hello. Below are the few things you may want to check.

- Does your Emacs show the inline images in other formats like PNG or SVG?
- Does pdf2svg command work and exist in a path that Emacs knows?
- Is org-inline-pdf-mode ON in the buffer? What happens if you manually do `M-x org-inline-pdf-mode`?

**Comment by uliw** [comment]
Update 2: all previous errors were caused by a botched startup file. Using vanilla 28.2 
- png shows as expected
- svg shows as expected
- pdf  show as expected
- pdf2svg works as expected

It appears that scimax modifies some of the org-image code in such a way that svg generation breaks

**Comment by shg** [comment]
@uliw Thank you for the info.

I confirmed the conflict with scimax. It seems scimax completely replaces `org-display-inline-images` with its own function and thus org-inline-pdf's function is not called when scimax is loaded. This might be solved by changing the way org-inline-pdf adds its advice but I haven't tested it yet.

So my understanding is for now you can make org-inline-pdf work by doing `M-x scimax-toggle-image-advice` correct? I haven't used scimax and I don't know what scimax features it would disable though.

**Comment by uliw** [comment]
yes, correct. Toggling climax-toggle-image-advice allows the inlining of pdfs. I'll chat with the author of scimax (a collection of tools for scientific writing)

**Comment by shg** [comment]
@uliw Thank you, I will mention the conflict with scimax in the README for now.

**Comment by uliw** [comment]
scimax-toggle-image-advice is a rarely used function, so save to have this default to nil in order to be compatible.
