### ISSUE TITLE
broken due to org-babel-temp-directory

### ISSUE THREAD

**Issue by dasoju** [shg/org-inline-pdf.el#8]
seeing following 
File mode specification error: (void-function org-babel-temp-directory) [2 times]
defvar: Symbol’s function definition is void: org-babel-temp-directory

org version : 9.5.5
Emacs version : 28.2

**Comment by shg** [comment]
Thank you for the report. I confirmed that a recent update introduced the issue. The update depends the function `org-babel-temp-directory` which is available only in newer versions of org.

Until I fix this problem, you can work around this by installing version 0.3 of `org-inline-pdf.el`. Please manually install it from this repository. It is also available from MELPA Stable.

**Comment by shg** [comment]
Fixed by dde04a2
